export const brandStatement1 = "A Software Engineer based in the San Francisco Bay Area.  When I’m not working I spend my time doing things that I love including gaming, archery, mountain biking, watching anime, or just learning how to do something new!" 

export const brandStatement2 = "As an engineer, I draw great satisfaction from the magic of building something new and seeing it come to life.  I love discovering my own solution to a problem, and enjoy the challenge of finding the best way to implement it.  Working with others who are more skilled than I am inspires me, and I always welcome the learning opportunity that it provides."

export const about1 = "I grew up in Carmel Valley which is about 30 minutes from Carmel by the Sea, and lived in that area until I was 17.  Eager to find my way, I moved around a bit for school and work, trying out different career paths.  I lived in New York for a while which was awesome, it was my first time living in a big city and I loved the culture there.  I also lived in Florida for a while before ending up in the Bay Area."

export const about2 = "When I started out I wasn’t sure what I wanted to do in life, so I went into Gemology on a recommendation from a close friend.  I enjoyed the field and had a great experience working for Tiffany & Co. in New York, but ultimately it wasn’t a good fit for me.  When I realized that, I decided to chase my dream of working with technology.  I moved back to California and started taking classes at the local community college.  I worked in restaurants while going to school to support myself, and ultimately got my BS in Computer Information Science."

export const about3 = "After that I worked in IT support for a while and was able to put some of my skills to use, however it still wasn’t quite what I was looking for.  I have always been fascinated with building software and am very excited to finally be pursuing my dream of becoming a software engineer currently at GA."

export const about4 = "In my personal life, I enjoy many activities from archery, surfing, and mountain biking, to gaming on my home built PC.  A personal goal of mine is to find a good D&D group and participate in an epic campaign.  Although I’ve dabbled in the past, I have never found the time or stayed in place long enough to find a committed group, and I love the idea of solving puzzles and facing challenges with a team in a creative setting while also making good friends."